case:
  represented_as: node
  preferred_id: id
  label_in_input: Subject

phenotypic feature:
  represented_as: node
  preferred_id: hp
  label_in_input: Phenotype

case to phenotype association:
  is_a: association
  represented_as: edge
  preferred_id: id
  label_in_input: HAS_PHENOTYPE
  label_as_edge: HAS_PHENOTYPE

phenotype to phenotype association:
  is_a: association
  represented_as: edge
  preferred_id: id
  label_in_input: IS_A
  label_as_edge: IS_A